### ISSUE TITLE
import mapping broke between v1.12.0 and v1.13.0

### ISSUE THREAD

**Issue by cosban** [deepmap/oapi-codegen#1093]
When running `go generate ./...` within the project directory, v1.12.0 will complete successfully whereas v1.13.0 will panic upon reaching second `go:generate` with the following stack when one oapi-codegen configuration uses import mapping to a separate spec:

```
> go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@v1.12.0
> go generate ./...
# success
> go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@v1.13.0 
> go generate ./...                                                   
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x100a6fd30]

goroutine 1 [running]:
github.com/deepmap/oapi-codegen/pkg/codegen.findSchemaNameByRefPath({0x140000c05e8?, 0x18?}, 0x14000206e10)
        $GOBIN/github.com/deepmap/oapi-codegen@v1.13.0/pkg/codegen/utils.go:861 +0x130
github.com/deepmap/oapi-codegen/pkg/codegen.refPathToGoType({0x140000c05e8, 0x18}, 0x0)
        $GOBIN/github.com/deepmap/oapi-codegen@v1.13.0/pkg/codegen/utils.go:355 +0x1d8
github.com/deepmap/oapi-codegen/pkg/codegen.refPathToGoType({0x140001da510, 0x26}, 0x38?)
        $GOBIN/github.com/deepmap/oapi-codegen@v1.13.0/pkg/codegen/utils.go:375 +0x34c
github.com/deepmap/oapi-codegen/pkg/codegen.RefPathToGoType(...)
        $GOBIN/github.com/deepmap/oapi-codegen@v1.13.0/pkg/codegen/utils.go:337
github.com/deepmap/oapi-codegen/pkg/codegen.GenerateGoSchema(0x140002a85d0, {0x140002b03e8?, 0x1, 0x1})
        $GOBIN/github.com/deepmap/oapi-codegen@v1.13.0/pkg/codegen/schema.go:235 +0xab0
github.com/deepmap/oapi-codegen/pkg/codegen.GenerateResponseDefinitions({0x1400009ebb0, 0x7}, 0x0?)
        $GOBIN/github.com/deepmap/oapi-codegen@v1.13.0/pkg/codegen/operations.go:762 +0x920
github.com/deepmap/oapi-codegen/pkg/codegen.OperationDefinitions(0x14000206e10, 0x0?)
        $GOBIN/github.com/deepmap/oapi-codegen@v1.13.0/pkg/codegen/operations.go:560 +0x55c
github.com/deepmap/oapi-codegen/pkg/codegen.Generate(0x14000206e10, {{0x140001a7ee8, 0x3}, {0x0, 0x0, 0x0, 0x1, 0x0, 0x1, 0x0, ...}, ...})
        $GOBIN/github.com/deepmap/oapi-codegen@v1.13.0/pkg/codegen/codegen.go:147 +0x6a8
main.main()
        $GOBIN/github.com/deepmap/oapi-codegen@v1.13.0/cmd/oapi-codegen/oapi-codegen.go:266 +0x11a4
doc.go:2: running "oapi-codegen": exit status 2
```
[This zip file](https://github.com/deepmap/oapi-codegen/files/11680959/reproduce.zip) can be used to reproduce the issue, but I have also laid out how to do from scratch below.

Must have the following initially empty directories:

* api/base/
* api/child/

base.yaml
```yaml
# base.yaml
package: api
generate:
  gin-server: true
  embedded-spec: true
  strict-server: true
  models: true
output: api/base/base.gen.go
output-options:
  skip-prune: true
```
child.yaml
```yaml
# child.yaml
package: api
generate:
  gin-server: true
  embedded-spec: true
  strict-server: true
  models: true
import-mapping:
   base.spec.yaml: import_bug/api/base
output: api/child/child.gen.go
```
base.spec.yaml
```yaml
# base.spec.yaml
openapi: 3.0.0
info:
  description: >-
    This base spec has models which are imported by the child spec
  title: base
  version: "1.0"
servers:
  - url: /base
paths:
  /pets:
    get: 
      description: |
        Returns pet from the system that the user has access to
      responses:
        '200':
          description: a successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
components:
  schemas:
    Pet:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        tag:
          type: string
```
child.spec.yaml
```yaml
# child.spec.yaml
openapi: 3.0.0
info:
  description: >-
    This child spec imports models from the base spec
  title: base
  version: "1.0"
servers:
  - url: /child
paths:
  /pets:
    get: 
      description: |
        Returns pet from the system that the user has access to
      responses:
        '200':
          description: a successful response
          content:
            application/json:
              schema:
                $ref: "base.spec.yaml#/components/schemas/Pet"
```
go.mod
```
module import_bug

go 1.18

require (
	github.com/deepmap/oapi-codegen v1.13.0
	github.com/getkin/kin-openapi v0.118.0
	github.com/gin-gonic/gin v1.9.1
)

require (
	github.com/apapsch/go-jsonmerge/v2 v2.0.0 // indirect
	github.com/bytedance/sonic v1.9.1 // indirect
	github.com/chenzhuoyu/base64x v0.0.0-20221115062448-fe3a3abad311 // indirect
	github.com/gabriel-vasile/mimetype v1.4.2 // indirect
	github.com/gin-contrib/sse v0.1.0 // indirect
	github.com/go-openapi/jsonpointer v0.19.6 // indirect
	github.com/go-openapi/swag v0.22.3 // indirect
	github.com/go-playground/locales v0.14.1 // indirect
	github.com/go-playground/universal-translator v0.18.1 // indirect
	github.com/go-playground/validator/v10 v10.14.0 // indirect
	github.com/goccy/go-json v0.10.2 // indirect
	github.com/google/uuid v1.3.0 // indirect
	github.com/invopop/yaml v0.2.0 // indirect
	github.com/josharian/intern v1.0.0 // indirect
	github.com/json-iterator/go v1.1.12 // indirect
	github.com/klauspost/cpuid/v2 v2.2.4 // indirect
	github.com/labstack/echo/v4 v4.10.2 // indirect
	github.com/labstack/gommon v0.4.0 // indirect
	github.com/leodido/go-urn v1.2.4 // indirect
	github.com/mailru/easyjson v0.7.7 // indirect
	github.com/mattn/go-colorable v0.1.13 // indirect
	github.com/mattn/go-isatty v0.0.19 // indirect
	github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd // indirect
	github.com/modern-go/reflect2 v1.0.2 // indirect
	github.com/mohae/deepcopy v0.0.0-20170929034955-c48cc78d4826 // indirect
	github.com/pelletier/go-toml/v2 v2.0.8 // indirect
	github.com/perimeterx/marshmallow v1.1.4 // indirect
	github.com/twitchyliquid64/golang-asm v0.15.1 // indirect
	github.com/ugorji/go/codec v1.2.11 // indirect
	github.com/valyala/bytebufferpool v1.0.0 // indirect
	github.com/valyala/fasttemplate v1.2.2 // indirect
	golang.org/x/arch v0.3.0 // indirect
	golang.org/x/crypto v0.9.0 // indirect
	golang.org/x/net v0.10.0 // indirect
	golang.org/x/sys v0.8.0 // indirect
	golang.org/x/text v0.9.0 // indirect
	google.golang.org/protobuf v1.30.0 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
)
```
doc.go
```go
//go:generate oapi-codegen --config base.yaml base.spec.yaml
//go:generate oapi-codegen --config child.yaml child.spec.yaml
package import_bug
```

**Comment by sanketrathi** [comment]
This was working till v1.12.4 for us, so definitely something to do with the latest (v1.13.0) release.
