### ISSUE TITLE
No schema in response

### ISSUE THREAD

**Issue by ShouheiNishi** [deepmap/oapi-codegen#1327]
When schema in content for response is not exist, code generation are failed.

```
$ cat issue.yaml
openapi: "3.0.1"
paths:
  /test:
    get:
      operationId: test
      responses:
        200:
          description: good
          content:
            application/json:
$ go run cmd/oapi-codegen/oapi-codegen.go -package issue -o issue.go issue.yaml && go test issue.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8ebab4]

goroutine 1 [running]:
github.com/deepmap/oapi-codegen/pkg/codegen.GenerateResponseDefinitions({0xc0002c7754, 0x4}, 0x0?)
        /home/nishi/free5gc-deb/free5gc/lib/oapi-codegen/pkg/codegen/operations.go:802 +0x854
github.com/deepmap/oapi-codegen/pkg/codegen.OperationDefinitions(0xc000152a20, 0x80?)
        /home/nishi/free5gc-deb/free5gc/lib/oapi-codegen/pkg/codegen/operations.go:596 +0x5a5
github.com/deepmap/oapi-codegen/pkg/codegen.Generate(0xc000152a20, {{0x7ffe6e25e3fb, 0x5}, {0x0, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, ...}, ...})
        /home/nishi/free5gc-deb/free5gc/lib/oapi-codegen/pkg/codegen/codegen.go:150 +0x7a5
main.main()
        /home/nishi/free5gc-deb/free5gc/lib/oapi-codegen/cmd/oapi-codegen/oapi-codegen.go:278 +0x13f8
exit status 2
$
```

**Comment by mromaszewicz** [comment]
The reporter saw a nil pointer dereference when a response content type had no schema. Running the exact spec from the issue against the current binary succeeds with exit code 0 and produces valid Go code. The fix is in pkg/codegen/schema.go:322 where GenerateGoSchema explicitly handles a nil SchemaRef by returning Schema{GoType: "interface{}"}, making the code path in GenerateResponseDefinitions (operations.go:1077) safe. No specific fix commit was identified but the nil guard is clearly present in the current code.

Closing as fixed. If you can still reproduce on a recent release, please reopen with the exact spec and version used.
