### ISSUE TITLE
Response unmarshal order

### ISSUE THREAD

**Issue by ShouheiNishi** [deepmap/oapi-codegen#1329]
In the case of the following definition file, if the HTTP status code is 204, response body should be ignored, but the current generated client code may treat body as JSON depending on the content-type header. 
Some servers return the Content-type which is "application/json" and an empty body, even when the status code is 204. In this case, decoding response body is failed and client code returns error.
I wish this interoperability problem will be resolved.

```
openapi: "3.0.1"
components:
  schemas:
    Test:
      type: object
      properties:
        field1:
          type: string
        field2:
          type: string
      required:
        - field1
        - field2
    Bad:
      type: object
      properties:
        reason:
          type: string
        detail:
          type: string
paths:
  /test:
    get:
      operationId: test
      requestBody:
        content:
          application/test+json:
            schema:
              $ref: "#/components/schemas/Test"
      responses:
        204:
          description: good
        default:
          description: bad
          content:
            application/bad+json:
              schema:
                $ref: "#/components/schemas/Bad"
```

**Comment by ShouheiNishi** [comment]
Test code is https://github.com/ShouheiNishi/oapi-codegen/commit/1a08d2ed970e48667382d70dde02d62dbd2f82a7.

```
$
$ git status
HEAD detached at 1a08d2e
nothing to commit, working tree clean
$ (cd internal/test ; go generate ./issues/issue-1329/...)
$ (cd internal/test ; go test ./issues/issue-1329/...)
--- FAIL: TestIssue1329 (0.00s)
    issue1329_test.go:29:
                Error Trace:    /home/nishi/free5gc-deb/free5gc/lib/oapi-codegen/internal/test/issues/issue-1329/issue1329_test.go:29
                Error:          Received unexpected error:
                                unexpected end of JSON input
                Test:           TestIssue1329
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6c572e]

goroutine 21 [running]:
testing.tRunner.func1.2({0x6fd380, 0x9c63f0})
        /usr/local/go/src/testing/testing.go:1545 +0x238
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1548 +0x397
panic({0x6fd380?, 0x9c63f0?})
        /usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/deepmap/oapi-codegen/internal/test/issues/issue-1329_test.TestIssue1329(0x0?)
        /home/nishi/free5gc-deb/free5gc/lib/oapi-codegen/internal/test/issues/issue-1329/issue1329_test.go:30 +0x10e
testing.tRunner(0xc0000836c0, 0x7889f0)
        /usr/local/go/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 1
        /usr/local/go/src/testing/testing.go:1648 +0x3ad
FAIL    github.com/deepmap/oapi-codegen/internal/test/issues/issue-1329 0.016s
FAIL
$
```

**Comment by mromaszewicz** [comment]
This is a comment from an automated bug scrub, after making a significant number of fixes to the code generation.

We reproduced this against the current `main`. The generated client now short-circuits on the status code before looking at `Content-Type`.

**Spec used** (`spec.yaml`):
```yaml
openapi: "3.0.1"
info:
  title: Test
  version: "1.0"
components:
  schemas:
    Test:
      type: object
      properties:
        field1: { type: string }
        field2: { type: string }
      required: [field1, field2]
    Bad:
      type: object
      properties:
        reason: { type: string }
        detail: { type: string }
paths:
  /test:
    get:
      operationId: test
      responses:
        204:
          description: good
        default:
          description: bad
          content:
            application/bad+json:
              schema:
                $ref: "#/components/schemas/Bad"
```

**Config used** (`config.yaml`):
```yaml
package: repro
output: client.gen.go
generate:
  models: true
  client: true
```

**Result:** in `ParseTestResponse` the `204` case is evaluated *before* the `Content-Type: json` case, so a 204 (even with `Content-Type: application/json` and an empty body) breaks out without attempting to decode a body:
```go
switch {
case rsp.StatusCode == 204:
	break // No content-type

case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
	var dest Bad
	if err := json.Unmarshal(bodyBytes, &dest); err != nil {
		return nil, err
	}
	response.ApplicationbadJSONDefault = &dest
}
```
The interoperability problem you described (204 + `application/json` empty body → decode error) no longer occurs. Closing as fixed.
