### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by draganApostolski** [deepmap/oapi-codegen#837]
Hi.

I am having troubles running the following `oapi-codegen` command:

`oapi-codegen -old-config-style -generate types -package notabene -o notabene_types.gen.go openapi.json`

I get the following error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x90 pc=0x104b94f30]

goroutine 1 [running]:
github.com/deepmap/oapi-codegen/pkg/codegen.GenerateGoSchema(0x1400026d878, {0x140002d0b68?, 0x1, 0x1})
        /Users/dragan.apostolski/go/pkg/mod/github.com/deepmap/oapi-codegen@v1.11.0/pkg/codegen/schema.go:205 +0x190
github.com/deepmap/oapi-codegen/pkg/codegen.GenerateBodyDefinitions({0x14000353650, 0xa}, 0x1400026d740)
        /Users/dragan.apostolski/go/pkg/mod/github.com/deepmap/oapi-codegen@v1.11.0/pkg/codegen/operations.go:526 +0x1d8
github.com/deepmap/oapi-codegen/pkg/codegen.OperationDefinitions(0x140001ea1a0)
        /Users/dragan.apostolski/go/pkg/mod/github.com/deepmap/oapi-codegen@v1.11.0/pkg/codegen/operations.go:435 +0x4c0
github.com/deepmap/oapi-codegen/pkg/codegen.Generate(0x16b66b74e?, {{0x16b66b74e, 0x8}, {0x0, 0x1, 0x0, 0x0, 0x1, 0x1}, {0x0, ...}, ...})
        /Users/dragan.apostolski/go/pkg/mod/github.com/deepmap/oapi-codegen@v1.11.0/pkg/codegen/codegen.go:132 +0x5a4
main.main()
        /Users/dragan.apostolski/go/pkg/mod/github.com/deepmap/oapi-codegen@v1.11.0/cmd/oapi-codegen/oapi-codegen.go:173 +0xd20
```

**Note**: There **may** be an issue with the `[open api spec schema](https://doc.notabene.id/)` from notabene, but it would be nice if the oapi-codegen interface handled this error and got us a user friendly error message back, so we can understand where the problem is.

**Comment by Burmuley** [comment]
Having the same issue with schema generate by apigit.com and oapi-codegen v2.4.1

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x100a04728]

goroutine 1 [running]:
github.com/oapi-codegen/oapi-codegen/v2/pkg/codegen.GenerateBodyDefinitions({0x1400034e8b0, 0xc}, 0x0?)
	/Users/burmuley/go/pkg/mod/github.com/oapi-codegen/oapi-codegen/v2@v2.4.1/pkg/codegen/operations.go:690 +0x38
github.com/oapi-codegen/oapi-codegen/v2/pkg/codegen.OperationDefinitions(0x140001d6780, 0xe0?)
	/Users/burmuley/go/pkg/mod/github.com/oapi-codegen/oapi-codegen/v2@v2.4.1/pkg/codegen/operations.go:602 +0x808
github.com/oapi-codegen/oapi-codegen/v2/pkg/codegen.Generate(_, {{0x140001f4200, 0x4}, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...})
	/Users/burmuley/go/pkg/mod/github.com/oapi-codegen/oapi-codegen/v2@v2.4.1/pkg/codegen/codegen.go:167 +0x740
main.main()
	/Users/burmuley/go/pkg/mod/github.com/oapi-codegen/oapi-codegen/v2@v2.4.1/cmd/oapi-codegen/oapi-codegen.go:307 +0x1214
internal/controllers/rest/model_utils.go:8: running "oapi-codegen": exit status 2
```
